# Generated by Django 4.1.5 on 2023-01-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_time', models.DateTimeField(blank=True, verbose_name='Conversation Time')),
            ],
        ),
    ]
