# Generated by Django 4.1.5 on 2023-01-09 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_post_delete_comment_delete_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='EventConfig',
        ),
    ]
